Concordium/concordium-reference-wallet-ios

- ConcordiumWallet.xcodeproj/project.pbxproj
Changed Testnet's Info.plist entry `PRODUCT_NAME` to equals  `$(TARGET_NAME)` 
Closes #31
> Update Testnet name

- ConcordiumWallet/Views/AccountsView/Recipient/SelectRecepient/SelectRecipientPresenter.swift
Sorting address book alphabetically. Closes #19
> Sort address book alphabetically

- ConcordiumWallet.xcodeproj/project.pbxproj
- ConcordiumWallet.xcodeproj/xcshareddata/xcschemes/ProdTestNet.xcscheme
- ConcordiumWallet/Resources/ConcordiumWalletTestNet-Info.plist
- ConcordiumWallet/Service/Network/ApiConstants.swift
Updated `BuildableName` property for `ProdTestNet` scheme
> General fixes

- ConcordiumWallet.xcodeproj/project.pbxproj
- ConcordiumWallet/AppCoordinator.swift
- ConcordiumWallet/Resources/ConcordiumWallet/Base.lproj/Localizable.strings
- ConcordiumWallet/Storyboards/Identity.storyboard
- ConcordiumWallet/Views/AccountsView/AccountDetails/AccountDetailsPresenter.swift
- ConcordiumWallet/Views/AccountsView/AccountDetails/AccountDetailsViewController.swift
- ConcordiumWallet/Views/AccountsView/AccountsPresenter.swift
- ConcordiumWallet/Views/AccountsView/AddMemo/AddMemoPresenter.swift
- ConcordiumWallet/Views/AccountsView/CreateAccount/CreateNicknamePresenter.swift
- ConcordiumWallet/Views/AccountsView/CreateAccount/RevealAttributesPresenter.swift
- ConcordiumWallet/Views/AccountsView/InitialAccount/GettingStartedPresenter.swift
- ConcordiumWallet/Views/AccountsView/InitialAccount/InitialAccountInfoPresenter.swift
- ConcordiumWallet/Views/AccountsView/InitialAccount/InitialAccountsCoordinator.swift
- ConcordiumWallet/Views/AccountsView/Recipient/AddRecepient/AddRecipientPresenter.swift
- ConcordiumWallet/Views/AccountsView/SendFunds/Confirmation/SendFundConfirmationPresenter.swift
- ConcordiumWallet/Views/AccountsView/SendFunds/SendFund/SendFundPresenter.swift
- ConcordiumWallet/Views/Identities/CreateIdentity/CreateIdentityCoordinator.swift
- ConcordiumWallet/Views/Identities/CreateIdentity/IdentityConfirmed/IdentityConfirmedViewController.swift
- ConcordiumWallet/Views/Identities/CreateIdentity/IdentityProviderList/IdentityProviderListPresenter.swift
- ConcordiumWallet/Views/Identities/CreateIdentity/IdentityProviderList/IdentityProviderListViewController.swift
- ConcordiumWallet/Views/Identities/IdentityList/IdentitiesViewController.swift
- ConcordiumWallet/Views/Login/TermsAndConditionsView/TermsAndConditionsPresenter.swift
- ConcordiumWallet/Views/MoreSection/About/AboutPresenter.swift
- ConcordiumWallet/Views/MoreSection/Export/ExportPresenter.swift
- ConcordiumWallet/Views/MoreSection/Update/UpdatePasswordCoordinator.swift
- ConcordiumWallet/Views/MoreSection/Update/UpdatePasswordPresenter.swift
- ConcordiumWallet/Views/Widgets/CreateAccountButtonWidgetPresenter.swift
- ConcordiumWallet/Views/Widgets/IdentityBaseInfoWidgetPresenter.swift
- ioscommon/Commons/ShowAlertProtocol.swift
Changes some labels and button text on the last page of the identity issuance flow and introduces an alert.
Closes #52 
* Updated localizations
* Updated button text and labels on last page of the identity issuance flow (`IdentityConfirmedViewController`)
* Refactored `ShowError` to `ShowAlert` and introduced generic `showRecoverableAlert` function
_Describe the changes that were needed.
> Last page update

- ConcordiumWallet/Resources/ConcordiumWallet/Base.lproj/Localizable.strings
- ConcordiumWallet/Storyboards/Base.lproj/Account.storyboard
- ConcordiumWallet/Views/AccountsView/Service/AccountsService.swift
Upgraded the drop GTU amount from 100 to 2000. Fixes the issue mentioned in #62.
> Bump GTU drop amount from 100 to 2000 GTU on Testnet

- ConcordiumWallet.xcodeproj/project.pbxproj
- ConcordiumWallet/Resources/ConcordiumWallet/Base.lproj/Localizable.strings
- ConcordiumWallet/Settings/AppSettings.swift
- ConcordiumWallet/Storyboards/Widget.storyboard
- ConcordiumWallet/Views/AccountsView/AccountsViewController.swift
- ConcordiumWallet/Views/Identities/IdentitiesCoordinator.swift
- ConcordiumWallet/Views/Identities/IdentityList/IdentitiesViewController.swift
- ConcordiumWallet/Views/MoreSection/About/AboutViewController.swift
- ConcordiumWallet/Views/Widgets/ContactSupportButtonWidgetViewController.swift
- ConcordiumWallet/Views/Widgets/CopyReferenceInfoWidgetPresenter.swift
- ConcordiumWallet/Views/Widgets/CopyReferenceInfoWidgetViewController.swift
- ConcordiumWallet/Views/Widgets/CopyReferenceWidgetPresenter.swift
- ConcordiumWallet/Views/Widgets/CopyReferenceWidgetViewController.swift
- ConcordiumWallet/Views/Widgets/WidgetAndLabelViewController.swift
- ioscommon/Commons/ShowIdentityFailureProtocol.swift
|  With Contact Support Button  | Without Contact Support Button   |
|---|---|
| ![Screenshot 2021-10-15 at 15 16 44](https://user-images.githubusercontent.com/8437817/137493353-022696b6-7f00-4a5f-bd7f-a95b44a30141.png) | ![Screenshot 2021-10-15 at 15 09 29](https://user-images.githubusercontent.com/8437817/137493404-36ffc865-30b0-4c65-b5fe-425f6690c8d8.png) |
Closes https://github.com/Concordium/concordium-reference-wallet-ios/issues/65
* Including build number in support mails
* Copying email body content instead of just the reference
* Update toast texts
* Info labels on `Account` screen (https://github.com/Concordium/concordium-reference-wallet-ios/issues/65)  …
> Copy reference additions

- ConcordiumWallet/Views/Login/RequestPasswordDelegate.swift
Closes #81 
The fallback of biometric authentication (passcode view) was actually dismissing the shared navigation controller when passcode typing is done. This is undesired behaviour as the navigation controller might hold other controllers as well, which is the case for the "Create new account flow". The changes make sure that only the `EnterPasswordViewController` (a.k.a passcode view) is being dismissed. 
> Fix new account flow being incomplete

- ConcordiumWallet/Resources/ConcordiumWallet/Base.lproj/Localizable.strings
- ConcordiumWallet/Storyboards/Base.lproj/Account.storyboard
Closes #94 
* Updated the reveal attributes description text
* Changed text color to black
> Reveal attributes update

- ConcordiumWallet/Resources/ConcordiumWallet/Base.lproj/Localizable.strings
- ConcordiumWallet/Service/StorageManager.swift
- ConcordiumWallet/Storyboards/Base.lproj/Account.storyboard
- ConcordiumWallet/StyledViews/Fonts.swift
- ConcordiumWallet/StyledViews/NavigationController/TransparentNavigationController.swift
- ConcordiumWallet/Views/AccountsView/AccountDetails/AccountDetailsViewController.swift
- ConcordiumWallet/Views/AccountsView/CreateAccount/CreateNicknameViewController.swift
- ConcordiumWallet/Views/Widgets/CopyReferenceInfoWidgetViewController.swift
- Podfile
- Podfile.lock
- ioscommon/Base/BaseNavigationController.swift
- ioscommon/Commons/Publisher+Utils.swift
Compiling the project with Xcode 13 and latest iOS 15 SDK. 
* Removed project warnings
* Introduced `UINavigationBarAppearance` which handles changes regarding the navigation bar in iOS 15.
* Replaced a deprecated `MDCTabBar` with `MDCTabBarView`
* Removed `MaterialComponents/Tabs+TabBarView` dependency and replace it with native iOS `UITextField`.
* Add two new localized strings  `accountDetails.transfers` and `accountDetails.identity_data` as it looked like hard-coded strings were used instead.
> iOS 15 and Xcode 13 Update

- ConcordiumWallet.xcodeproj/project.pbxproj
- ConcordiumWallet/Storyboards/Base.lproj/Account.storyboard
- ConcordiumWallet/Storyboards/Login.storyboard
- ConcordiumWallet/Storyboards/SendFund.storyboard
- ConcordiumWallet/Views/AccountsView/AddMemo/AddMemoViewController.swift
- ConcordiumWallet/Views/AccountsView/CreateAccount/CreateNicknamePresenter.swift
- ConcordiumWallet/Views/AccountsView/CreateAccount/CreateNicknameViewController.swift
- ConcordiumWallet/Views/AccountsView/Recipient/AddRecepient/AddRecipientViewController.swift
- ConcordiumWallet/Views/AccountsView/SendFunds/SendFund/SendFundViewController.swift
- ConcordiumWallet/Views/Identities/CreateIdentity/IdentityProviderList/IdentityProviderListPresenter.swift
- ConcordiumWallet/Views/Login/PasswordViews/EnterPasswordViewController.swift
- ConcordiumWallet/Views/MoreSection/Export/ExportPresenter.swift
- ioscommon/Base/BaseViewController.swift
- ioscommon/Base/KeyboardDismissableBaseViewController.swift
- ioscommon/Commons/ShowAlertProtocol.swift
Fixed various keyboard issues and streamlined the dismissal of the keyboard. 
| ![Screenshot 2021-11-16 at 11 00 14](https://user-images.githubusercontent.com/8437817/141979643-2cba314e-1832-4546-98ef-52577715f1db.png) | ![Screenshot 2021-11-16 at 11 00 29](https://user-images.githubusercontent.com/8437817/141979655-416b4edb-30be-457d-9182-8b5470ed0807.png)  |  ![Screenshot 2021-11-16 at 11 00 48](https://user-images.githubusercontent.com/8437817/141979660-716d308c-bfea-4156-a81f-3361c01fecf6.png)  |
|---|---|---|
| ![Screenshot 2021-11-16 at 11 18 16](https://user-images.githubusercontent.com/8437817/141979666-472a2c4b-9e66-4594-a364-807d2c5a0dc9.png)  | ![Screenshot 2021-11-16 at 11 22 24](https://user-images.githubusercontent.com/8437817/141979668-c69d525e-407b-4b23-8164-e42c8128bbba.pn …
> Keyboard issues

- ConcordiumWallet.xcodeproj/project.pbxproj
- ConcordiumWallet/Resources/ConcordiumWallet/Base.lproj/Localizable.strings
- ConcordiumWallet/Resources/ConcordiumWalletMainNet-Info.plist
- ConcordiumWallet/Resources/ConcordiumWalletStagingNet-Info.plist
- ConcordiumWallet/Resources/ConcordiumWalletTestNet-Info.plist
- ConcordiumWallet/Views/Identities/IdentitiesCoordinator.swift
- ConcordiumWallet/Views/Widgets/CopyReferenceInfoWidgetPresenter.swift
- ConcordiumWallet/Views/Widgets/CopyReferenceInfoWidgetViewController.swift
Change hardcorded string that included a reference to Notabene
Used dynamic values for ip name and ip support email in CopeReferenceInfoWidget
> Multiple identity providers copy reference fix

- ConcordiumWallet/Storyboards/Widget.storyboard
Fixes non-scrollable content in the Identity failure screen.  Fix #87 
Embedded the content of the WidgetAndLabelViewController in a stackview, which is in turn embedded in a scrollview
> Make Identity Failed Screen scrollable

- ConcordiumWallet/Views/AccountsView/AccountsPresenter.swift
- ConcordiumWallet/Views/Identities/IdentitiesCoordinator.swift
- ConcordiumWallet/Views/Identities/IdentityList/IdentitiesPresenter.swift
- ConcordiumWallet/Views/Widgets/ContactSupportButtonWidgetPresenter.swift
Updated fallback email to concordium's suppot email. Fix #87 
Instead of "" we use Concordium's support email if the IP doesn't have one specified
> Updated fallback email to concordium's

- ConcordiumWallet.xcodeproj/project.pbxproj
- ConcordiumWallet/Resources/ConcordiumWallet/Base.lproj/Localizable.strings
- ConcordiumWallet/Views/AccountsView/AccountsViewController.swift
- ConcordiumWallet/Views/Identities/CreateIdentity/IdentityConfirmed/IdentityConfirmedViewController.swift
- ConcordiumWallet/Views/Widgets/IdentityBaseInfoWidgetPresenter.swift
- ioscommon/Commons/ShowAlertProtocol.swift
Showing extra alert warning if the user dismisses the default backup alert. 
| Make backup flow first alert | Make backup flow extra alert   | Make backup flow extra alert dismissal |  
|---|---|---|
| ![Watch the video](https://user-images.githubusercontent.com/8437817/148211313-c399ee6a-d382-4bef-bd51-b5ba05592583.mp4) |  ![Watch the video](https://user-images.githubusercontent.com/8437817/148212726-65c12b4e-eafb-46d4-aa0a-3ceebe409860.mp4) | ![Watch the video](https://user-images.githubusercontent.com/8437817/148213661-69bf75bd-1a39-44be-b930-5594804d4139.mp4) | 
* Refactor `ShowAlert` component in order to support multiple actions with completion handlers
* Bumped  build version
By submitting the contribution I accept the terms and …
> Extra backup warning alert

- ConcordiumWallet.xcodeproj/project.pbxproj
- ConcordiumWallet/Resources/ConcordiumWallet-mock-Info.plist
- ConcordiumWallet/Resources/ConcordiumWalletMainNet-Info.plist
- ConcordiumWallet/Resources/ConcordiumWalletStagingNet-Info.plist
- ConcordiumWallet/Resources/ConcordiumWalletTestNet-Info.plist
Bumping the version number
Bumped app version number to 1.2
_Describe the changes that were needed.
> Bumped version to 1.2

- ConcordiumWallet/Resources/ConcordiumWallet/Base.lproj/Localizable.strings
- ConcordiumWallet/Settings/AppSettings.swift
- ConcordiumWallet/Storyboards/Base.lproj/Account.storyboard
- ConcordiumWallet/Storyboards/Identity.storyboard
- ConcordiumWallet/Views/AccountsView/AccountsCoordinator.swift
- ConcordiumWallet/Views/AccountsView/AccountsPresenter.swift
- ConcordiumWallet/Views/AccountsView/AccountsViewController.swift
- ConcordiumWallet/Views/MoreSection/Export/ExportPresenter.swift
Closes https://github.com/Concordium/concordium-reference-wallet-ios/issues/139
* Introduced new backup missing banner view
* Updated localizations
> Missing backup banner

- ConcordiumWallet/Resources/ConcordiumWallet/Base.lproj/Localizable.strings
- ConcordiumWallet/Settings/AppSettings.swift
- ConcordiumWallet/Views/MoreSection/MoreCoordinator.swift
- ConcordiumWallet/Views/MoreSection/VerifyIdsAndAccounts/SanityChecker.swift
- ConcordiumWallet/Views/RootView/MainTabBarController.swift
Closes #147
* Showing backup alert warning when app updates 
*  Introduced new `lastKnownAppVersionSinceBackupWarning` key in `AppSettings` 
> Backup warning on app update

- ConcordiumWallet.xcodeproj/project.pbxproj
Bump build no for prod and staging
updated build number
> bumped build no on mainnet and staging

- ConcordiumWallet.xcodeproj/project.pbxproj
- ConcordiumWallet/Service/MobileWallet.swift
- ConcordiumWallet/Views/MoreSection/Import/IdentityImporter.swift
- ConcordiumWallet/Views/MoreSection/VerifyIdsAndAccounts/SanityChecker.swift
Fix importing after missing keys as described in #173
Fixes #173 
> Import over missing keys fix

- ConcordiumWallet.xcodeproj/project.pbxproj
- ConcordiumWallet/Resources/ConcordiumWallet/Base.lproj/Localizable.strings
- ConcordiumWallet/Storyboards/Base.lproj/Account.storyboard
- ConcordiumWallet/Storyboards/SendFund.storyboard
- ConcordiumWallet/Views/AccountsView/CreateAccount/CreateNicknameViewController.swift
- ConcordiumWallet/Views/AccountsView/SendFunds/SendFund/SendFundPresenter.swift
- ConcordiumWallet/Views/AccountsView/SendFunds/SendFund/SendFundViewController.swift
- ioscommon/Commons/UIButton+Extensions.swift
- ioscommon/Commons/UIControl+Extensions.swift
Closes #159 
* Implemented "Send all" button.
* Updated localizations.
* Fixed various layout issues on `SendFunds` screen. 
* Fixed keyboard issues on `SendFunds` screen.
* Fixed keyboards issues on `CreateNickname` screen.
* Styling updates. 
> Send All button

- ConcordiumWallet/Storyboards/Base.lproj/Account.storyboard
Fixes #168 
Update constraints in Storyboard
> fixed create identity button placement

- ConcordiumWallet.xcodeproj/project.pbxproj
- ConcordiumWallet/Resources/ConcordiumWallet/Base.lproj/Localizable.strings
- ConcordiumWallet/Storyboards/Base.lproj/Account.storyboard
- ConcordiumWallet/Views/AccountsView/AccountDetails/AccountDetailsCoordinator.swift
- ConcordiumWallet/Views/AccountsView/AccountDetails/AccountDetailsPresenter.swift
- ConcordiumWallet/Views/AccountsView/AccountDetails/AccountDetailsViewController.swift
- ConcordiumWallet/Views/AccountsView/AccountDetails/BurgerMenu/AccountDetailsBurgerMenu/BurgerMenuAccountDetailsPresenter.swift
- ConcordiumWallet/Views/AccountsView/AccountDetails/BurgerMenu/BurgerMenuOptionCell.swift
- ConcordiumWallet/Views/AccountsView/AccountDetails/BurgerMenu/BurgerMenuPresenter.swift
- ConcordiumWallet/Views/AccountsView/AccountDetails/BurgerMenu/BurgerMenuViewController.swift
Refactored burger menu to allow for more options (is needed for both hiding the decrypt for March release and for delegating)
Moved the unlock button in case some of the amounts are undecrypted 
Fixed #190 - point 3
Made the menu options dynamic
Added decrypt option to the menu for the shielded (exactly as Android)
> Refactored burger menu to allow reuse and dynamic options

- ConcordiumWallet.xcodeproj/project.pbxproj
- ConcordiumWallet/Resources/ConcordiumWallet/Base.lproj/Localizable.strings
- ConcordiumWallet/Views/AccountsView/AccountDetails/AccountDetailsViewController.swift
- ConcordiumWallet/Views/MoreSection/About/AboutViewController.swift
Minor UI issue fixes
Fixes #207
Fixes #208 
Fixes #210
Small UI and localisation update
> Fixes/minor UI fixes

- ConcordiumWallet.xcodeproj/project.pbxproj
- ConcordiumWallet/Views/AccountsView/AccountsPresenter.swift
- ConcordiumWallet/Views/AccountsView/SendFunds/SendFund/SendFundPresenter.swift
Fixes #209 and #211
Verifying address validity when enabling send button
Only subtracting the cost for "send all" if balance is public
> Fixes #209 and #211

- ConcordiumWallet/Resources/ConcordiumWallet/Base.lproj/Localizable.strings
- ConcordiumWallet/Storyboards/Stake.storyboard
- ConcordiumWallet/Views/Stake/Baking/PoolSettings/BakerPoolSettingsPresenter.swift
- ConcordiumWallet/Views/Stake/Baking/PoolSettings/BakerPoolSettingsViewController.swift
Update baker pool settings screen
- Updated strings
- Set settings in datahandler
> Updated pool settings screen

- ConcordiumWallet.xcodeproj/project.pbxproj
- ConcordiumWallet/Model/TransferCostParameters.swift
- ConcordiumWallet/Model/TransferCostRange.swift
- ConcordiumWallet/Resources/ConcordiumWallet/Base.lproj/Localizable.strings
- ConcordiumWallet/Views/AccountsView/Service/TransactionsService.swift
- ConcordiumWallet/Views/Stake/Baking/AmountInput/BakerAmountInputPresenter.swift
- ConcordiumWallet/Views/Stake/Baking/BakingCoordinator.swift
- ConcordiumWallet/Views/Stake/Common/AmountInput/StakeAmountInputValidator.swift
- ConcordiumWallet/Views/Stake/Common/AmountInput/StakeAmountInputViewController.swift
- ConcordiumWallet/Views/Stake/Common/StakeDataHandler.swift
- ConcordiumWallet/Views/Stake/Delegation/AmountInput/DelegationInputPresenter.swift
- ioscommon/Commons/Publisher+Utils.swift
Implement the amount input screen for baking.
Added the baking amount input screen, small refactors to related APIs.
> baking amount input

- ConcordiumWallet/Model/AutoGenerated/BakerPoolResponse.swift
- ConcordiumWallet/Resources/ConcordiumWallet/Base.lproj/Localizable.strings
- ConcordiumWallet/Views/Onboarding/OnboardingCarousel/OnboardingCarouselViewController.swift
- ConcordiumWallet/Views/Stake/Baking/PoolSettings/BakerPoolSettingsPresenter.swift
- ConcordiumWallet/Views/Stake/Baking/Status/BakerPoolStatusPresenter.swift
- Scripts/createModel.sh
It must be possible to stop baking after it has been registered.
Fixes a couple of bugs with stop baking
> fix a couple of bug with stop baking

- .github/workflows/test.yml
- fastlane/Fastfile
- tests runs now on each push (also for main branch)
- tests are no more treated as "deployment"
> Fastlane & CI improvements

- ConcordiumWallet.xcodeproj/project.pbxproj
- ConcordiumWallet/Model/ContractUpdate/ContractUpdateParams.swift
- ConcordiumWallet/Model/Schema/Schema.swift
- ConcordiumWallet/Model/WalletConenctError.swift
- ConcordiumWallet/Model/WalletConnectError.swift
- ConcordiumWallet/Views/WalletConnect/AccountSelect/WalletConnectAccountSelectView.swift
- ConcordiumWallet/Views/WalletConnect/AccountSelect/WalletConnectAccountSelectViewModel.swift
- ConcordiumWallet/Views/WalletConnect/WalletConnectCoordinator.swift
- Extract helper functions for responding with or without errors.
- Reject proposals with unexpected "required" namespaces.
- Define errors as big nested enum.
> Improve error handling

- ConcordiumWallet/Views/WalletConnect/AccountSelect/WalletConnectAccountItemView.swift
Using Button instead of VStack makes the entire area tappable.
> WalletConnect: Select Account: UI button fix

- ConcordiumWallet.xcodeproj/project.pbxproj
- ConcordiumWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- ConcordiumWallet/Views/WalletConnect/WalletConnectCoordinator.swift
_Describe the changes that were needed.
> Fix reject session crash

- ConcordiumWallet/Service/Network/NetworkManager.swift
- ConcordiumWallet/Views/RecoveryPhrase/RecoveryPhraseInputPresenter.swift
- ConcordiumWallet/Views/SeedIdentities/SeedIdentitiesService.swift
I removed the leftover comments of code that is no longer used.
> Rmove redundant commented out code

- ConcordiumWallet.xcodeproj/project.pbxproj
- ConcordiumWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
_Describe the purpose of the pull request, link to issue describing the problem, etc.
> Update realm version

- ConcordiumWallet.xcodeproj/project.pbxproj
- ConcordiumWallet/Model/CIS2/CIS2TokenSelectionRepresentable.swift
- ConcordiumWallet/Service/StorageManager.swift
- ConcordiumWallet/Storyboards/SendFund.storyboard
- ConcordiumWallet/Views/AccountsView/AccountDetails/AccountDetailsCoordinator.swift
- ConcordiumWallet/Views/AccountsView/AccountDetails/AccountDetailsPresenter.swift
- ConcordiumWallet/Views/AccountsView/AccountDetails/TokenDetails/TokenDetailsView.swift
- ConcordiumWallet/Views/AccountsView/AccountDetails/TokenLookup/CIS2Service.swift
- ConcordiumWallet/Views/AccountsView/AccountDetails/TokenLookup/CIS2TokensCoordinator.swift
- ConcordiumWallet/Views/AccountsView/AccountDetails/TokenSelectionView/CIS2TokenSelectView.swift
- ConcordiumWallet/Views/AccountsView/SendFunds/SendFund/SendFundPresenter.swift
- ConcordiumWallet/Views/AccountsView/SendFunds/SendFund/SendFundViewController.swift
- ConcordiumWallet/Views/AccountsView/SendFunds/SendFundTokenSelection.swift
- ConcordiumWallet/Views/AccountsView/SendFunds/SendFundsCoordinator.swift
- ConcordiumWalletTests/HelperClasses/Mocks/StorageManagerMockHelper.swift
This pull requests introduces a new token details screen showing metadata of CIS2 token. Also, alows the user to remove the token from local database, to stop displaying in account details.
> [CIS-2] token details screen

- ConcordiumWallet.xcodeproj/project.pbxproj
- ConcordiumWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- ConcordiumWallet/AppDelegate.swift
- ConcordiumWallet/Model/CIS2/CIS2TokenMetadataDetails.swift
- ConcordiumWallet/Model/CIS2/CIS2TokenSelectionRepresentable.swift
- ConcordiumWallet/Service/StorageManager.swift
- ConcordiumWallet/Storyboards/Base.lproj/Account.storyboard
- ConcordiumWallet/Views/AccountsView/AccountDetails/AccountDetailsPresenter.swift
- ConcordiumWallet/Views/AccountsView/AccountDetails/AccountDetailsViewModel.swift
- ConcordiumWallet/Views/AccountsView/AccountDetails/AccountTokens/AccountTokensTableViewCell.swift
- ConcordiumWallet/Views/AccountsView/AccountDetails/AccountTokens/AccountTokensViewController.swift
- ConcordiumWallet/Views/AccountsView/AccountDetails/TokenSelectionView/CIS2TokenSelectView.swift
- ConcordiumWallet/Views/RecoveryPhrase/RecoveryPhraseInputPresenter.swift
- ConcordiumWalletTests/HelperClasses/Mocks/StorageManagerMockHelper.swift
- ioscommon/Commons/RealmHelper.swift
Fixes following issues related with CIS-2 implementation:
* Tokens (FT and NFT) balance shown incorrect after adding to the account [CBW-1324)](https://concordium.atlassian.net/browse/CBW-1324)
* Incorrect NFT balance presentation [CBW-1323](https://concordium.atlassian.net/browse/CBW-1323)
* Fix showing search results for tokens that don't have `unique` property [CBW-1317](https://concordium.atlassian.net/browse/CBW-1317)
* display “Tokens” tab as default in account details screen [CBW-1307](https://concordium.atlassian.net/browse/CBW-1307)
[CBW-1323]: https://concordium.atlassian.net/browse/CBW-1323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CBW-1317]: https://concordium.atlassian.net/browse/CBW-1317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY …
> [CIS-2] Bug triage bug fixes

- ConcordiumWallet.xcodeproj/project.pbxproj
- ConcordiumWallet/Service/StorageManager.swift
- ConcordiumWallet/Views/AccountsView/AccountDetails/AccountTokens/AccountTokensViewController.swift
- ConcordiumWallet/Views/AccountsView/AccountDetails/TokenDetails/TokenDetailsView.swift
- ConcordiumWallet/Views/AccountsView/AccountDetails/TokenLookup/CIS2Service.swift
- ConcordiumWallet/Views/AccountsView/AccountDetails/TokenSelectionView/CIS2TokenSelectView.swift
- ConcordiumWalletTests/HelperClasses/Mocks/StorageManagerMockHelper.swift
- fastlane/Fastfile
Solves: 
[CBW-1344](https://concordium.atlassian.net/browse/CBW-1344)
[CBW-1380](https://concordium.atlassian.net/browse/CBW-1380)
[CBW-1379](https://concordium.atlassian.net/browse/CBW-1379)
[CBW-1344]: https://concordium.atlassian.net/browse/CBW-1344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CBW-1380]: https://concordium.atlassian.net/browse/CBW-1380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CBW-1379]: https://concordium.atlassian.net/browse/CBW-1379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix CIS2 related bugs

- ConcordiumWallet/Views/AccountsView/AccountDetails/ButtonSlider.swift
- ConcordiumWallet/Views/AccountsView/AccountDetails/TokenDetails/TokenDetailsView.swift
- ConcordiumWallet/Views/AccountsView/AccountDetails/TokenLookup/CIS2Service.swift
- ConcordiumWallet/Views/AccountsView/AccountDetails/TokenLookup/TokenLookupView.swift
- unhide send button in account details screen [CBW-1386](https://concordium.atlassian.net/browse/CBW-1386)
- increase limit for tokens displayed in contract index search [CBW-1359](https://concordium.atlassian.net/browse/CBW-1359)
- hide `show raw metadata` button [CBW-1340](https://concordium.atlassian.net/browse/CBW-1340)
[CBW-1386]: https://concordium.atlassian.net/browse/CBW-1386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CBW-1359]: https://concordium.atlassian.net/browse/CBW-1359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CBW-1340]: https://concordium.atlassian.net/browse/CBW-1340?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CIS2 pre-release bug fixes

- ConcordiumWallet/Resources/ConcordiumWallet/Base.lproj/Localizable.strings
https://concordium.atlassian.net/browse/CBW-1543
> [CBW-1543] Baking action button should be renamed to Validation

- ConcordiumWallet.xcodeproj/project.pbxproj
- ConcordiumWallet/Model/CIS2/CIS2TokenMetadataDetails.swift
- ConcordiumWallet/Model/CIS2/CIS2TokenSelectionRepresentable.swift
- ConcordiumWallet/Storyboards/SendFund.storyboard
- ConcordiumWallet/Views/AccountsView/AccountDetails/AccountTokens/AccountTokensViewController.swift
- ConcordiumWallet/Views/AccountsView/AccountDetails/TokenDetails/TokenDetailsView.swift
- ConcordiumWallet/Views/AccountsView/AccountDetails/TokenLookup/CIS2Service.swift
- ConcordiumWallet/Views/AccountsView/AccountDetails/TokenLookup/TokenLookupView.swift
- ConcordiumWallet/Views/AccountsView/AccountDetails/TokenSelectionView/CIS2TokenSelectView.swift
- ConcordiumWallet/Views/AccountsView/SendFunds/SendFund/SendFundPresenter.swift
- ConcordiumWallet/Views/AccountsView/SendFunds/SendFund/SendFundViewController.swift
- ConcordiumWallet/Views/Stake/Baking/AmountInput/BakerAmountInputPresenter.swift
- ConcordiumWalletTests/CIS2TokenSelectionRepresentableTests.swift
- ioscommon/Commons/RealmHelper.swift
CBW-1640 Shield CCDs with the new account
CBW - 1638 Add proper CIS-2 token image preview: add thumbnail and display images due to [docs](https://proposals.concordium.software/CIS/cis-2.html#token-metadata-json)
CBW-1478 Fix CIS-2 token local db persistency 
CBW-1626  Fix restaking logic, in case when user want update options without changing stake amount
CBW-1643 Fix contract update tx cost refresh logic
> release 1.5.0

- ConcordiumWallet/Views/AccountsView/AccountDetails/TokenSelectionView/CIS2TokenSelectViewModel.swift
Fix CIS2 token look up view pagination logic
Add zero ids handler, in case when contract has one token
- [x ] My code follows the style of this project.
- [x ] The code compiles without warnings.
- [x ] I have performed a self-review of the changes.
- [x ] I have documented my code, in particular the intent of the
- [ x] (If necessary) I have updated the CHANGELOG.
> Fix token look up view pagination logic

- ConcordiumWallet/Storyboards/SendFund.storyboard
- ConcordiumWallet/Views/AccountsView/SendFunds/SendFund/SendFundPresenter.swift
Estimation transaction fee is not always the same for the same transaction.
Fix CIS2 token look list image
Fix transaction fee update logic while user input amount of token to send. 
Replaced SDWebImage with Async image due to hight memory consumption during list tokens scroll
> Contract update failed insufficient energy fix

- ConcordiumWallet.xcodeproj/project.pbxproj
- ConcordiumWallet/Resources/ConcordiumWallet-mock-Info.plist
- ConcordiumWallet/Resources/ConcordiumWalletMainNet-Info.plist
- ConcordiumWallet/Resources/ConcordiumWalletStagingNet-Info.plist
- ConcordiumWallet/Resources/ConcordiumWalletTestNet-Info.plist
Add Encryption Usage data. Update version
> Add Non-Exempt Encryption version bumped

- ConcordiumWallet.xcodeproj/project.pbxproj
Remove `TermsAndConditionsView.swift` duplication inside `project.pbxproj` which prevents app to archive on ci, but locally runs normal without any error 😐
> Fix project structure

- CHANGELOG.md
- ConcordiumWallet.xcodeproj/project.pbxproj
Removed automatic code signing, and it works 🥶
> removed automatic code sign from test net env

- CHANGELOG.md
- ConcordiumWallet.xcodeproj/project.pbxproj
> Bump Testnet version number

- ConcordiumWallet/Resources/ConcordiumWalletStagingNet-Info.plist
Removed testate compliance code
> fix staging build
