Concordium/concordium-reference-wallet-ios

ConcordiumWallet/Views/Identities/CreateIdentity/CreateIdentityCoordinator.swift

Making sure all identities and accounts are cleaned up if the identity creation flow is aborted by the user. 
Closes #35

Cleanup both identities and accounts if flow is aborted

---

ConcordiumWallet/Views/Identities/CreateIdentity/CreateIdentityCoordinator.swift

@jens-concordium reported: 
> The camera permission thing is solved now, but it has lead to a new problem
> 
> So, if the permission is denied, the dialog is shown as intended. If the user then goes to the settings, allows the app to use the camera, and then goes back to the app, the intro flow is skipped and there is a "rogue" account in the Accounts page list
That happens because the (i)OS terminates the app each time a permission is toggled on or off. That might also happen if the user manually terminates the app.  To solve this issue we need to observe for the so called `willTerminate` event and respectively perform a cleanup. The cleanup includes calling the function discussed in https://github.com/Concordium/concordium-reference-wallet-ios/pull/44

Cleanup accounts when app terminates

---

ConcordiumWallet.xcodeproj/project.pbxproj
ConcordiumWallet/Service/MobileWallet.swift

* Treating "commitments randomness" as optional while updating passcode.
* Bumped app (Testnet) version (17)
Closes #54

Fix passcode change failure

---

ConcordiumWallet/Views/MoreSection/Import/IdentityImporter.swift

Integration testing - Importing a file produced by the Android app (@jensvesti) did not include the randomness
The reason for it was that the randomness was not taken into account while importing the file. 
Simple check whether the import has randomness included or not

Check for commitments randomness while importing accounts from a file

---

ConcordiumWallet/Model/Export/EncryptionMetadata.swift

As mentioned in [here](#50) the `encryptionMethod` and `keyDerivationMethod` fields were missing from an export file. 
[Some time ago the fields were made static](https://github.com/Concordium/concordium-reference-wallet-ios/commit/f287e2b41580ba3253f92453d2fe2c9388a9c167#diff-dbe20a501ac086b56fee70e24926060357f3f1db4c310489158c5fb9de50222fR10)
* Remove static modifiers 
* Set default values for `encryptionMethod` and `keyDerivationMethod` upon initialization
Closes #50

Include encryptionMethod and keyDerivationMethod in metadata

---

ConcordiumWallet.xcodeproj/project.pbxproj
ConcordiumWallet/AppCoordinator.swift
ConcordiumWallet/Service/StorageManager.swift
ConcordiumWallet/Views/AccountsView/InitialAccount/InitialAccountsCoordinator.swift
ConcordiumWallet/Views/Identities/CreateIdentity/CreateIdentityCoordinator.swift

* Collect all cleanup funcs in `StorageManager`
* Cleanup accounts without address upon login*
* Bump project version (18)
_* That will cover the scenario when the user changes a permission from the `Settings` app and the iOS restarts the app. Unfortunately iOS does not provide us with such a system event and the best we can do is to basically cleanup the accounts without address upon login_
Closes #24

Accounts identity cleanup

---

ConcordiumWallet/Resources/ConcordiumWallet/Base.lproj/Localizable.strings
ConcordiumWallet/Resources/ConcordiumWalletTestNet-Info.plist
ConcordiumWallet/Settings/AppSettings.swift
ConcordiumWallet/Views/AccountsView/AccountsViewController.swift
ConcordiumWallet/Views/Identities/IdentityList/IdentitiesViewController.swift
ConcordiumWallet/Views/MoreSection/About/AboutViewController.swift
ConcordiumWallet/Views/Widgets/ContactSupportButtonWidgetViewController.swift
ioscommon/Base/AppConstants.swift
ioscommon/Commons/MailHelper.swift
ioscommon/Commons/SupportMailProtocol.swift

#65 
- Updated texts on alert dialog shown during identity failure
- Now it's possible to include optional `CC` for both native and third-party mail composer
- Two new static vars in `AppSettings` - `appVersion` and `iOSVersion` 

Update identity issuance dialog

---

ConcordiumWallet.xcodeproj/project.pbxproj
ConcordiumWallet/Resources/ConcordiumWallet/Base.lproj/Localizable.strings
ConcordiumWallet/Service/StorageManager.swift
ConcordiumWallet/Settings/AppSettings.swift
ConcordiumWallet/Views/AccountsView/AccountsCoordinator.swift
ConcordiumWallet/Views/AccountsView/AccountsPresenter.swift
ConcordiumWallet/Views/AccountsView/AccountsViewController.swift
ConcordiumWallet/Views/Widgets/IdentityBaseInfoWidgetPresenter.swift
ioscommon/Commons/ShowAlertProtocol.swift

Closes #79 
- Saving pending accounts addresses in user preferences (that will allow showing the notification across app sessions)
- Checking regularly (on view did appear event) if the pending accounts are being finalized
- Show notification alert when an account is being finalized

Notification on succesful new account 

---

ConcordiumWallet/Service/Network/ApiConstants.swift

When the identity provider experiences an error in the identity creation flow, it redirects the browser to the callback URL with a `#error=...` component instead of a `#code_uri=...` component. The current logic for parsing the URL spuriously succeeds in this case, since it does not correctly check that `#code_uri` actually occurs in the URL.
This PR implements a fix that will only succeed if the `#code_uri` component is set.
This addresses #100 and at least the most apparent cause of #107.
Change `parseCallbackUri` to only succeed if there is just one `#code_uri=` component.

Fix parsing the callback from the ID provider

---

ConcordiumWallet/Storyboards/Login.storyboard
ConcordiumWallet/Views/Login/PasswordViews/EnterPasswordViewController.swift
ConcordiumWallet/Views/MoreSection/Update/ChangePasswordPresenter.swift
ioscommon/Commons/LoadProtocol.swift

https://github.com/Concordium/concordium-reference-wallet-ios/issues/101
Closes #101 
Showing activity indicator while user is updating password/passcode

Show activity indicator while changing passcode/password

---

Podfile
Podfile.lock

Closes #103 
Crash info: 
```
Realm files of format version 22 is not supported by this version of Realm
```
Seems strange that it worked after bumping the Realm version to `10.19.0`. That means Realm has introduce backwards compatibility sometime in between. 

Updated Realm to latest 10.19.0

---

ConcordiumWallet.xcodeproj/project.pbxproj
ConcordiumWallet/Model/AccountSubmissionStatus.swift
ConcordiumWallet/Resources/ConcordiumWallet/Base.lproj/Localizable.strings
ConcordiumWallet/Service/StorageManager.swift
ConcordiumWallet/StyledViews/NavigationController/TransparentNavigationController.swift
ConcordiumWallet/Views/AccountsView/AccountsPresenter.swift
ConcordiumWallet/Views/AccountsView/AccountsViewController.swift
ConcordiumWallet/Views/AccountsView/Service/AccountsService.swift
ConcordiumWallet/Views/Identities/IdentitiesService.swift
ConcordiumWallet/Views/Login/LoginCoordinator.swift
ConcordiumWallet/Views/Login/PasswordViews/EnterPasswordViewController.swift
ConcordiumWallet/Views/Login/RequestPasswordDelegate.swift
ConcordiumWallet/Views/MoreSection/Import/IdentityImporter.swift
ioscommon/Commons/UIViewController+Additions.swift

* Delivering batch notification when multiple accounts are finalized https://github.com/Concordium/concordium-reference-wallet-ios/issues/79#issuecomment-964864489
* Fix issue with the passcode's navbar color if the app locks during the identity/account creation process. 
|![Screenshot 2021-11-11 at 09 06 14](https://user-images.githubusercontent.com/8437817/141281599-7912d047-1049-4246-82ab-23eee2932ebe.png)|
|-|
* Zipping all network requests for accounts statuses instead of firing them in a for loop
* `UIViewController` extension var for checking whether the controller is shown on screen or not. Particularly useful to decide whether or not to show finalized account notification 
* `AccountSubmissionStatus` wrapper model
* Set light preferred status bar style for pass code view …

Finalized account alerts fixes 

---

ConcordiumWallet.xcodeproj/project.pbxproj
ConcordiumWallet/Storyboards/Base.lproj/Account.storyboard
ConcordiumWallet/Views/AccountsView/CreateAccount/CreateNicknameViewController.swift
ioscommon/Base/BaseViewController.swift

| iPhone SE  |  iPhone 13 |
|---|---|
| ![1](https://user-images.githubusercontent.com/8437817/142642693-a979ecca-bdd9-46dd-a574-ad66050dc0e2.mp4)  | ![2](https://user-images.githubusercontent.com/8437817/142642704-92e798ce-16c6-40a7-9487-3b03a329a851.mp4) | 
Addresses the last comment in #104 
To begin with, the whole view is very problematic since it has text field, button and a the whole thing is within a scroll view and a keyboard that comes from below. On top of everything we have those huge whitespaces which are not really suitable for smaller screen devices.
Anyway I have applied a fix and removed the scrollview as it was the main culprit of the bug. The scrollview (I believe) was intended to serve smaller screen devices, meaning if the screen is too small then you can scroll the …

More keyboard fixes

---

ConcordiumWallet/Views/AccountsView/AccountDetails/AccountTransactionsData/TransactionViewModel.swift

Transactions sent/received by an alias where shown in the list with "main account" name instead of "alias account" name, when viewing from the "main account" of the alias. Fixes #127
Both transferSource and transferDestination are now looked up in address book, no matter if the current account is the source or destination (instead of using the account name directly)

Removed optimisation for lookup as it was causing issues with aliases

---

ConcordiumWallet.xcodeproj/project.pbxproj
ConcordiumWallet/Views/AccountsView/AccountDetails/AccountDetailsViewController.swift
ConcordiumWallet/Views/AccountsView/AccountsViewController.swift
ConcordiumWallet/Views/Identities/IdentityList/IdentitiesViewController.swift

There seems that there are some issues with Realm objects that are used in timer handlers after app enters background. As per Apple recommendation, timers should be invalidated when app is no longer active ( https://developer.apple.com/documentation/uikit/app_and_environment/scenes/preparing_your_ui_to_run_in_the_background ). Should fix #130 
Added observer for appWillResignActive and appDidBecome active in all three view controllers where timers are used for refresh. The refresh timers for a viewController are stopped when app is deactivated and are scheduled again when app is activated.
- link: …

Stop timer when app resigns active

---

ConcordiumWallet/Settings/AppSettings.swift
ConcordiumWallet/Views/AccountsView/AccountsCoordinator.swift
ConcordiumWallet/Views/AccountsView/AccountsPresenter.swift

The backup warning should only be shown after new account is created.
* Renamed `UserDefaultKey`  `backupPerformed`  to `needsBackupWarning` and inverted it's value. This way we make sure that the backup warning is not shown after a device restore  etc. 

Show backup banner warning only after new account is created

---

ConcordiumWallet.xcodeproj/project.pbxproj
ConcordiumWallet/AppCoordinator.swift
ConcordiumWallet/Model/Database/AccountEntity.swift
ConcordiumWallet/Resources/ConcordiumWallet/Base.lproj/Localizable.strings
ConcordiumWallet/Service/ErrorMapper.swift
ConcordiumWallet/Service/MobileWallet.swift
ConcordiumWallet/Service/ServicesProvider.swift
ConcordiumWallet/Service/StorageManager.swift
ConcordiumWallet/Settings/AppSettings.swift
ConcordiumWallet/Views/AccountsView/AccountsCoordinator.swift
ConcordiumWallet/Views/AccountsView/AccountsPresenter.swift
ConcordiumWallet/Views/AccountsView/AccountsViewController.swift
ConcordiumWallet/Views/AccountsView/CreateAccount/RevealAttributesPresenter.swift
ConcordiumWallet/Views/Identities/IdentitiesCoordinator.swift
ConcordiumWallet/Views/Identities/IdentityList/IdentitiesViewController.swift
ConcordiumWallet/Views/Login/PasswordViews/EnterPasswordViewController.swift
ConcordiumWallet/Views/Login/PasswordViews/LoginPresenter.swift
ConcordiumWallet/Views/Login/PasswordViews/RequestExportPasswordPresenter.swift
ConcordiumWallet/Views/MoreSection/Export/ExportService.swift
ConcordiumWallet/Views/MoreSection/Import/IdentityImporter.swift
ConcordiumWallet/Views/MoreSection/Import/ImportService.swift
ConcordiumWallet/Views/MoreSection/Import/Importer.swift
ConcordiumWallet/Views/MoreSection/MoreCoordinator.swift
ConcordiumWallet/Views/MoreSection/MoreMenuPresenter.swift
ConcordiumWallet/Views/MoreSection/MoreMenuViewController.swift
ConcordiumWallet/Views/MoreSection/VerifyIdsAndAccounts/SanityChecker.swift
ConcordiumWallet/Views/RootView/MainTabBarController.swift
ConcordiumWallet/Views/Widgets/CopyReferenceInfoWidgetViewController.swift
ioscommon/Base/Coordinator.swift
ioscommon/Commons/ShowIdentityFailureProtocol.swift

Mediates the issues that appear after a user backs up his phone and restores it.
Handles invalid export files
Updates intro info text
Marks the app data as not restorable through iPhone backups so we won't end up having accounts stored on the phone with no keys
Fixes #141 
Fixes #140 
Mark app data as not restorable by iPhone backup
There is a sanity check that is performed automatically after login and which can also be triggered manually after clicking the ValidateIds and accounts in the menu.
The missing keys for identities are now handled gracefully (the user is given the option to delete identities and accounts with missing keys)
The accounts with missing keys are marked as readonly if the user chooses to keep them
If the user keeps an identity with missing keys and tries to make an …

Backup fix

---

ConcordiumWallet/Views/MoreSection/MoreCoordinator.swift

Closes https://github.com/Concordium/concordium-reference-wallet-ios/issues/139
* Setting `AppSettings.needsBackupWarning` setting to `false` when backup is performed via `More->Export`

Fix backup warning

---

ConcordiumWallet.xcodeproj/project.pbxproj
ConcordiumWallet/Resources/ConcordiumWallet/Base.lproj/Localizable.strings
ConcordiumWallet/Views/MoreSection/Export/ExportService.swift

Closes #150
* Updated localizations
* Renamed exported backup file to `concordium-backup.concordiumwallet`

Change text in backup reminders

---

ConcordiumWallet/AppCoordinator.swift
ConcordiumWallet/Settings/AppSettings.swift
ConcordiumWallet/Views/AccountsView/InitialAccount/InitialAccountsCoordinator.swift
ConcordiumWallet/Views/MoreSection/VerifyIdsAndAccounts/SanityChecker.swift

Currently the backup warning alert is shown after a fresh app install, which should not be the case
Relates to #147 
* Made `hasRunBefore` a setting in `AppSettings` 
* Checking for `hasRunBefore` before showing the backup warning alert

Don't show backup warning on fresh install

---

ConcordiumWallet/Views/MoreSection/VerifyIdsAndAccounts/SanityChecker.swift

Fixes https://github.com/Concordium/concordium-reference-wallet-ios/issues/150#issuecomment-1023023248
* Setting `AppSettings.needsBackupWarning=true` 
* Passing completion handler in order to reload accounts after backup warning dismissal. 

Reload Accounts after dismiss of backup warning

---

ConcordiumWallet.xcodeproj/project.pbxproj
ConcordiumWallet/Views/Identities/CreateIdentity/CreateIdentityCoordinator.swift

Fixes #162 
Pending account is now stored when Account is created as part of an identity

Display dialog and box if the account is finished while user is waiting in the identities screen

---

ConcordiumWallet/Views/AccountsView/AccountsPresenter.swift
ConcordiumWallet/Views/AccountsView/AccountsViewController.swift
ConcordiumWallet/Views/Identities/IdentityList/IdentitiesPresenter.swift

Fix race condition on the AccountsPresenter that was usually causing it to crash when the identity issuance finished with an error while the app was closed
Fixes #130
Subscribing to app appDidBecomeActive and willResignActiveNotification in viewDidAppear which will make it not being triggered when opening the app for the first time
Removed some unused code

Fix identity background crash

---

ConcordiumWallet/Model/Database/AccountEntity.swift
ConcordiumWallet/Views/AccountsView/AccountsPresenter.swift
ConcordiumWallet/Views/AccountsView/Service/AccountsService.swift
ioscommon/Commons/RealmHelper.swift

Updated the way we check for shielded transactions on an account to avoid issues when importing a new account
It is now determined whether an account has received shielded transactions based on the inputAmounts

Updated the way we check for shielded transactions

---

ConcordiumWallet/Views/AccountsView/SendFunds/SendFund/SendFundPresenter.swift
ioscommon/Commons/PermissionHelper.swift

Scan QR on send funds should also check for camera permissions. 
Implemented a check for camera permission before showing the QR scanner. Also ensure that completion handlers are dispatched to the main thread from the permission callback.

align camera permissions checks

---

ConcordiumWallet/AppCoordinator.swift
ConcordiumWallet/Resources/ConcordiumWallet/Base.lproj/Localizable.strings

The user should be presented with a warning if a baker pool they are delegating to is closing.
A warning is now presented to the user on startup if one or more of their accounts are delegating to a closing pool.

implement waring when a baker pool is closing

---

ConcordiumWallet.xcodeproj/project.pbxproj
ConcordiumWallet/Model/AutoGenerated/ChainParametersResponse.swift
ConcordiumWallet/Model/TransferCostParameters.swift
ConcordiumWallet/Resources/ConcordiumWallet/Base.lproj/Localizable.strings
ConcordiumWallet/Resources/RegisterDelegationOnboarding/delegation_intro_flow_en_2.html
ConcordiumWallet/Resources/RegisterDelegationOnboarding/delegation_intro_flow_en_3.html
ConcordiumWallet/Resources/RegisterDelegationOnboarding/delegation_intro_flow_en_4.html
ConcordiumWallet/Resources/RegisterDelegationOnboarding/delegation_intro_flow_en_5.html
ConcordiumWallet/Service/Network/ApiConstants.swift
ConcordiumWallet/Views/AccountsView/AccountDetails/AccountDetailsViewModel.swift
ConcordiumWallet/Views/AccountsView/StakeService.swift
ConcordiumWallet/Views/Stake/Common/StakeDataHandler.swift
ConcordiumWallet/Views/Stake/Delegation/AmountInput/DelegationInputPresenter.swift
ConcordiumWallet/Views/Stake/Delegation/DelegationDataHandler.swift
ConcordiumWallet/Views/Stake/Delegation/PoolSelection/DelegationPoolSelectionPresenter.swift
ConcordiumWallet/Views/Stake/Delegation/PoolSelection/DelegationPoolSelectionViewController.swift
ConcordiumWallet/Views/Stake/Delegation/Status/DelegationStatusPresenter.swift
ConcordiumWallet/mock/4.1.2.RX_backend_accBalance.json
ConcordiumWallet/mock/5.2.2.RX_backend_chain_parameters.json
Scripts/createModel.sh

The L-Pool is being renamed to passive delegation. This pull request addresses this.
- UI has been updated according to changes described
- References has been renamed to reflect the new name
- Calls to mobile wallet and backend has been updated to reflect the new names

changed references to l-pool to passive

---

ConcordiumWallet.xcodeproj/project.pbxproj
ConcordiumWallet/Model/AppSettingsResponse.swift
ConcordiumWallet/Resources/ConcordiumWallet/Base.lproj/Localizable.strings
ConcordiumWallet/Service/Network/ApiConstants.swift
ConcordiumWallet/Service/ServicesProvider.swift
ConcordiumWallet/Views/AccountsView/AccountsPresenter.swift
ConcordiumWallet/Views/AccountsView/AppSettingsService.swift
ioscommon/Commons/URL+queryParameters.swift

Enable wallet-proxy to inform about or force users to update the app from App Store.
Fetch appSettings from wallet-proxy.
Parse data and show alert if needed.

Force update functionality

---

.github/workflows/build+test.yml
ConcordiumWallet.xcodeproj/project.pbxproj
ConcordiumWallet.xcodeproj/xcshareddata/xcschemes/Mock.xcscheme
ConcordiumWallet/Model/Environment.swift
ConcordiumWallet/Views/AccountsView/AccountsPresenter.swift
ConcordiumWalletTests/HelperClasses/StorageManagerMockHelper.swift
ConcordiumWalletTests/Presentation/AttributesFormatterTests.swift
ConcordiumWalletTests/Presentation/RecoveryPhrase/InputPhraseTests.swift

Ensure that #302 can be merged.
- Update CI check workflow: Bump Swift version to accommodate expected SwiftPM version. This requires using a newer OS version. After these changes, it's necessary to sign the build for running unit tests. This was added.
- Fix broken tests and code that's only used/broken when running tests.

CI: Update Swift version and fix test setup

---

ConcordiumWallet/Presentation/AttributesFormatter.swift
ConcordiumWalletTests/Presentation/AttributesFormatterTests.swift

Currently, the "document type" attribute is empty when it doesn't match any of the currently known values.
Fall back to the raw "document type" value when no localized string is matched.
Resolves https://concordium.atlassian.net/browse/CBW-907.
I don't think the base branch of this PR is the correct one to merge into, but I don't know which one is..?
I also cannot run the tests due to compiler errors like `/Users/mo/work/concordium-reference-wallet-ios/ConcordiumWallet/Model/Environment.swift:28:16 Cannot convert value of type 'String' to specified type 'Environment'` (fixing this results in other errors elsewhere).

Fall back to raw "document type" when no localized string is matched

---

ConcordiumWallet/AppCoordinator.swift
ConcordiumWallet/Views/Login/LoginCoordinator.swift
ConcordiumWalletTests/Coordinators/LoginCoordinatorTests.swift

After upgrading an existing wallet though ​[CBW-910](unreleased) and accepting terms and condition, the user is prompted to create a new password. This would allow an attacker to reset the password on a stolen phone, and is undesired from perspective of user experience.
I reasured that after current T&C version response is fetched, we do check if user has a password already set. 
I covered the missing scenario with adequate tests.
[CBW-910]: https://concordium.atlassian.net/browse/CBW-910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CBW-1031] fix app flow when new t&c available password is created

---

ConcordiumWallet/Resources/ConcordiumWallet-mock-Info.plist
ConcordiumWallet/Resources/ConcordiumWalletMainNet-Info.plist
ConcordiumWallet/Resources/ConcordiumWalletStagingNet-Info.plist
ConcordiumWallet/Resources/ConcordiumWalletTestNet-Info.plist

The app crashes when user tries to use Notabene to add identity. 
I added `NSMicrophoneUsageDescription ` property to *.plist files in order to request user for microphone usage permission.

Fix app crashing on camera user verification via Notabene

---

ConcordiumWallet/AppCoordinator.swift
ConcordiumWallet/Views/AccountsView/AccountsCoordinator.swift
ConcordiumWallet/Views/AccountsView/AccountsPresenter.swift
ConcordiumWallet/Views/MoreSection/MoreCoordinator.swift

Moved `showWalletConnectScanner` from `AppCoordinator` to `AccountsCoordinator` (and from protocol `AccountsPresenterDelegate` to new one `WalletConnectDelegate`). `AccountsPresenter` gets `AppCoordinator` (as a `WalletConnectDelegate`) in a new init parameter.

Move showWalletConnectScanner from AppCoordinator

---

ConcordiumWallet/Views/WalletConnect/WalletConnectCoordinator.swift

On proposal, expect `chains` value `ccd:testnet` or `ccd:mainnet` depending on the network the app is built for.
This change also ensures that the QR code scanner is dismissed on proposal error.
Alternative to https://github.com/Concordium/concordium-reference-wallet-ios/pull/337.

WalletConnect: Use correct ID for network

---

ConcordiumWallet/Model/AutoGenerated/ChainParametersResponse.swift
ConcordiumWallet/mock/5.2.2.RX_backend_chain_parameters.json

Election difficultly is no longer present in P6, which causes failure of parameter parsing for GET /v0/chainParameters.
Since this is not used by the wallet anyhow, it is removed from the expected parameters.

Remove election difficulty from expected parameters (legacy wallet)

---

ConcordiumWallet/Model/AutoGenerated/ChainParametersResponse.swift
ConcordiumWallet/mock/5.2.2.RX_backend_chain_parameters.json

Election difficultly is no longer present in P6, which causes failure of parameter parsing for `GET /v0/chainParameters`.
Since this is not used by the wallet anyhow, it is removed from the expected parameters.

Remove election difficulty from expected parameters.

---

CHANGELOG.md
ConcordiumWallet/Service/Network/NetworkManager.swift

It has been reported that for some of the identity providers unicode characters are displayed wrong. It was caused by the fix, that tried to 'walkaround' invalid JSON format that is sent by DTS, wrapping it in unecessary quotation marks.
Affects: https://concordium.atlassian.net/browse/CBW-1083
I removed the fix that removed backslashes from json string.
I temporarily added support for cases where JSON is embedded within string.

[CBW-1083] Remove the 'fix' that manually removed backslashes from wallet recovery requests

---

ConcordiumWallet/Model/AutoGenerated/GASRewards.swift
ConcordiumWallet/Model/AutoGenerated/MakeCreateTransferRequest.swift
ConcordiumWallet/Service/MobileWallet.swift

Removed field `finalizationProof` from `GASRewards` which was previously unused and from chain parameters v2 also [missing](https://developer.concordium.software/concordium-grpc-api/#concordium.v2.GasRewardsCpv2) from the API.
Also changed `finalizationRewardCommission` in `MakeCreateTransferRequest` to a string like it was previously done (in [`823955b`](https://github.com/Concordium/concordium-reference-wallet-ios/commit/823955bfb84d38a0e3689c01042b3c01b306d557#diff-e58c27121216c2044222445446d54233fddf1a2d5ccaea6fb4931b57e440e784R20)) for `transactionFeeCommission` and `bakingRewardCommission` to fix [CBW-659](https://concordium.atlassian.net/browse/CBW-659) as we saw that same issue again for this field.
Fixes [CBW-1143](https://concordium.atlassian.net/browse/CBW-1143).
[CBW-659]: …

Fix baking and delegation on P6

---

ConcordiumWallet/Views/AccountsView/AccountDetails/AccountDetailsPresenter.swift
ConcordiumWallet/Views/AccountsView/AccountDetails/AccountDetailsViewController.swift

Ensure that toggling of the setting for displaying shielded transfers is picked up by the UI.
Revert changes [#357](https://github.com/Concordium/concordium-reference-wallet-ios/pull/357/files#diff-2a831347698dfe816d7be4bcdb3b9208ab59a0cfaed29da4e3dbb6e93f326c00L223-L243) that broke toggling of shielded transfers.
Fixes https://concordium.atlassian.net/browse/CBW-1387.

Revert changes that broke toggling of shilelded transfers

---

ConcordiumWallet/Views/Stake/Baking/ComissionSettings/BakerCommissionSettingsView.swift

The text explaining the Pool settings has been updated to user the term “validator” instead of “baker“

[CBW-1538] Change "baker" to "validator" in Pool settings screen

---

ConcordiumWallet/Resources/ConcordiumWallet-mock-Info.plist
ConcordiumWallet/Resources/ConcordiumWalletMainNet-Info.plist
ConcordiumWallet/Resources/ConcordiumWalletTestNet-Info.plist

Apple rejected our app due to missing `Privacy - Microphone Usage Description`
Added following message to info.plist files:
`To ensure a secure and seamless user experience, our app might use the microphone for a liveness check. The microphone is exclusively used during the identity creation process.`

Update microphone usage description

---

ConcordiumWallet/Views/AccountsView/AccountDetails/AccountTokens/AccountTokensViewController.swift

CCD balance under Fungible tab should not include shielded balance, it should show same value as “Balance total”
Now the label show `finalizedBalance` instead of `forecastTotalBalance`

[CBW-1480] Disable shielded balance under Fungible tab

---

ConcordiumWallet/Views/AccountsView/AccountDetails/AccountDetailsViewController.swift

Option to request for CCD should be shown as long as there’s no transaction log on this screen. 
There was unnecessary setting of `isHidden` bool for transaction list view. It has been removed.

[CBW-1388] show as long as there’s no transaction log on this screen

---

ConcordiumWallet/Service/Network/NetworkManagerProtocol.swift
ConcordiumWallet/Views/WalletConnect/ApproveScreen/WalletConnectActionRequestView.swift
ConcordiumWallet/Views/WalletConnect/WalletConnectCoordinator.swift
ioscommon/Commons/RealmHelper.swift

When app is in WalletConnect session it keeps on showing the same balance as it was at the time of establishing connection for each request.
I added fetching of account balance for each request so it should the most up to date amount.

[CBW-1125] Update balance on signature approval screen

---

ConcordiumWallet.xcodeproj/project.pbxproj
ConcordiumWallet/Views/AccountsView/AccountDetails/TokenLookup/CIS2Service.swift
ConcordiumWallet/Views/AccountsView/AccountDetails/TokenSelectionView/CIS2TokenSelectView.swift
ConcordiumWallet/Views/AccountsView/AccountDetails/TokenSelectionView/CIS2TokenSelectViewModel.swift
ConcordiumWallet/Views/AccountsView/AccountDetails/TokenSelectionView/SearchTokenViewModel.swift

Add search toke by `tokenId` functionality. 
Update view logic to search tokens instead of filter out already loaded items
Extended `CIS2Service.swift` by adding  `func getTokenMetadataPair(metadata: CIS2TokensMetadata) async throws -> [(CIS2TokensMetadataItem, CIS2TokenMetadataDetails)]` such as using in both viewModels.

Add search token by tokenId functionality

---

ConcordiumWallet/Views/AccountsView/AccountDetails/TokenSelectionView/CIS2TokenSelectView.swift

Add support `.svg` image format for `CIS2Token` search list
Replaced AsyncImage with SDWebImage

Fix  CIS2Token search list display images

---

ConcordiumWallet/Resources/ConcordiumWalletMainNet-Info.plist
ConcordiumWallet/Resources/ConcordiumWalletStagingNet-Info.plist
ConcordiumWallet/Resources/ConcordiumWalletTestNet-Info.plist

To release an app we need to specify `App Encryption Export Compliance Code`  in app .plist
Add export code for all targets

Add encryption export compliance code

---

ConcordiumWallet/Views/AccountsView/SendFunds/SendFund/SendFundPresenter.swift

The Send All button currently does not trigger the logic chain needed to update its state.
Added functionality to update the Send button state after the amount to send value is changed.

Fix `Send All` button logic, while sending ccd's

---

ConcordiumWallet/Views/AccountsView/AccountDetails/TokenLookup/CIS2Service.swift
ConcordiumWallet/Views/UnshiedSunset/UnshiedSunsetView.swift

Fixed wallet checksum verification issue
Added method to verify checksum.
https://github.com/user-attachments/assets/98e9ab27-0689-4f90-9093-3645722ec5b1

Fixed wallet checksum verification issue
